org: tsingis
app: rss-feeds
service: rss-feeds

provider:
  name: aws
  stage: ${opt:stage, "live"}
  runtime: python3.13
  runtimeManagement: auto
  versionFunctions: false
  architecture: x86_64
  region: ${opt:region, "eu-north-1"}
  memorySize: 256
  timeout: 15
  logRetentionInDays: 90
  environment:
    RSS_FEED_URLS: ${env:RSS_FEED_URLS}
    BUCKET_NAME: ${env:BUCKET_NAME}
    SNS_TOPIC_ARN: ${env:SNS_TOPIC_ARN}

functions:
  handler:
    handler: handler.handler
    role: arn:aws:iam::${aws:accountId}:role/RSSFeedLambdaFunctionRole
    events:
      - schedule: cron(0 5 * * ? *)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt

package:
  patterns:
    - "!**"
    - "handler.py"
