block-list-secret-scan: []
branch: master
custom-tool-name: Checkov
directory:
  - .
evaluate-variables: true
external-modules-download-path: .external_modules
mask: []
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_AWS_18
  - CKV_AWS_26
  - CKV_AWS_50
  - CKV_AWS_115
  - CKV_AWS_116
  - CKV_AWS_117
  - CKV_AWS_144
  - CKV_AWS_145
  - CKV_AWS_158
  - CKV_AWS_173
  - CKV_AWS_272
  - CKV_AWS_297
  - CKV_AWS_338
  - CKV2_AWS_62
summary-position: top
