name: deploy
on:
  push:
    branches:
      - master
    paths:
      - "**"
      - "!README.md"
      - "!.gitignore"
      - "!cloudformation/**"
      - "!.github/**"
      - ".github/workflows/deploy.yaml"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy
        run: npm run-script deploy
        env:
          RSS_FEED_URLS: ${{ secrets.RSS_FEED_URLS }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
